live2d:
  enable: true
  scriptFrom: local
  model: 
      use: live2d-widget-model-hijiki #模型选择
  display: 
      position: left #模型位置
      width: 225      #模型宽度
      height: 350      #模型高度
  mobile: 
      show: ture      #是否在手机端显示